version: '3'
services:
  spring-boot-demo-env-variables:
    image: 'tosharathshetty/sample-spring-boot-on-kubernetes:latest'
    ports:
      - "8081:8081"   
      - "8080:8080"    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo   
    environment:
      - JDBC_DRIVERCLASSNAME=org.firebirdsql.jdbc.FBDriver-overridden
